<?php
return [
    'goods_category' => [
        'principal_food' => '主食',
        'subsidiary_food' => '副食',
        'drink' => '饮料',
        'medicines' => '药品',
    ],
    'expiry_level' => [
        1 => 45, // expiry level 1 的临期期限是 45 天，以下类推。
        2 => 20,
        3 => 15,
        4 => 10,
        5 => 5,
        6 => 2,
        7 => -999999,
    ],
    'goods' => [
        'principal_food' => [
            'rice' => '大米',
            'flour' => '面粉',
            'brown_rice' => '糙米',
            'wholewheat' => '全麦',
            'maize' => '玉米',
            'millet' => '小米',
            'rhubarb_rice' => '大黄米',
            'oats' => '燕麦',
            'barley' => '大麦',
            'sorghum' => '高粱',
            'buckwheat' => '荞麦',
            'mung' => '绿豆',
            'red_bean' => '赤小豆',
            'hyacinth_Bean' => '扁豆',
            'kidney_bean' => '芸豆',
            'vicia_faba' => '蚕豆',
            'potato' => '土豆',
            'sweet_potato' => '红薯',
            'cassava' => '木薯',
            'taro' => '芋头',
            'chinese_yam' => '山药',
            'others' => '其他',
        ],
        'subsidiary_food' => [
            '方便面',
            '蔬菜',
            '火腿肠',
            '香肠',
            '其他',
        ],
        'drink' => [
            '牛奶',
            '可乐',
            '雪碧',
            '橘子味汽水',
            '其他',
        ],
        'medicines' => [
            '钙片',
            '氯化钾片',
            '冠心病-xxx',
            '其他',
        ],
    ],
];
